server:
  port: 8080
  servlet:
    context-path: /sushix_api

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=SushiX;encrypt=false;
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  signerKey: "e026njxhGoX+RrhfBN7xULmfWxnLMcbD4OXC2GIuOZIxbHgOGQDWw94G6gyNxbz7"

springdoc:
  swagger-ui:
    path: /swagger-ui.html